{"kind":"symbol","identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError\/badResponse(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"badResponse","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":""},{"type":"text","text":" "},{"text":"Vigram would normally expect to receive “ICY 200 OK” as the first message.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If any other first message is received,"},{"type":"text","text":" "},{"text":"the NtripTask emits this error with the data of the first message.","type":"text"}],"type":"paragraph"}],"name":"Note"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Connecting to a Ntrip mountpoint failed, since we received a bad response."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/ntriptaskerror\/badresponse(_:)"]}],"metadata":{"roleHeading":"Case","title":"NtripTaskError.badResponse(_:)","externalID":"s:9VigramSDK14NtripTaskErrorO11badResponseyAC10Foundation4DataVcACmF","symbolKind":"case","role":"symbol","modules":[{"name":"VigramSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badResponse"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripTask":{"abstract":[{"text":"A NtripTask requests RTK data over a NTRIP connection.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NtripTask"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTask","navigatorTitle":[{"kind":"identifier","text":"NtripTask"}],"url":"\/documentation\/vigramsdk\/ntriptask","role":"symbol","title":"NtripTask"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"role":"collection","url":"\/documentation\/vigramsdk","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"type":"icon","identifier":"logo.png"}],"type":"topic","title":"VigramSDK"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripTaskError":{"role":"symbol","url":"\/documentation\/vigramsdk\/ntriptaskerror","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError","title":"NtripTaskError","type":"topic","abstract":[{"text":"NtripTaskError lists different errors that can be emitted by ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTask","type":"reference"},{"type":"text","text":" implementations."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NtripTaskError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NtripTaskError"}]},"logo.png":{"alt":"Vigram logo.","variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}],"identifier":"logo.png","type":"image"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/NtripTaskError/badResponse(_:)":{"url":"\/documentation\/vigramsdk\/ntriptaskerror\/badresponse(_:)","type":"topic","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/NtripTaskError\/badResponse(_:)","title":"NtripTaskError.badResponse(_:)","abstract":[{"text":"Connecting to a Ntrip mountpoint failed, since we received a bad response.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badResponse"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}]}}}