{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/errordescription-6oo8g"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-6oo8g","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"errorDescription","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:9VigramSDK19AuthenticationErrorO","extendedModule":"Foundation","modules":[{"name":"VigramSDK"}]},"hierarchy":{"paths":[["doc:\/\/VigramSDK\/documentation\/VigramSDK","doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError","doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/LocalizedError-Implementations"]]},"references":{"doc://VigramSDK/documentation/VigramSDK":{"role":"collection","title":"VigramSDK","abstract":[],"identifier":"doc:\/\/VigramSDK\/documentation\/VigramSDK","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk"},"doc://VigramSDK/documentation/VigramSDK/AuthenticationError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/localizederror-implementations"},"doc://VigramSDK/documentation/VigramSDK/AuthenticationError/errorDescription-6oo8g":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-6oo8g","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/errordescription-6oo8g"},"doc://VigramSDK/documentation/VigramSDK/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"identifier":"doc:\/\/VigramSDK\/documentation\/VigramSDK\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/vigramsdk\/authenticationerror"}}}