{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"notConnected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"BluetoothServiceError.notConnected(_:)","externalID":"s:9VigramSDK21BluetoothServiceErrorO12notConnectedyAC10Foundation4UUIDVcACmF","symbolKind":"case","modules":[{"name":"VigramSDK"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"},{"text":"(","kind":"text"},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"text":")","kind":"text"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)"},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError/notConnected(_:)":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)","title":"BluetoothServiceError.notConnected(_:)","url":"\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notConnected"},{"kind":"text","text":"("},{"text":"UUID","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4UUIDV"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}],"kind":"symbol"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothService":{"title":"BluetoothService","navigatorTitle":[{"kind":"identifier","text":"BluetoothService"}],"role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","kind":"symbol","url":"\/documentation\/vigramsdk\/bluetoothservice","abstract":[{"type":"text","text":"A BluetoothService is used to handle bluetooth connections."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BluetoothService"}],"type":"topic"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"images":[{"identifier":"logo.png","type":"icon"}],"kind":"symbol","title":"VigramSDK","abstract":[],"type":"topic","url":"\/documentation\/vigramsdk","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","role":"collection"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"BluetoothServiceError","kind":"identifier"}],"type":"topic","title":"BluetoothServiceError","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError","kind":"symbol","abstract":[{"text":"BluetoothServiceError lists different errors that can be propagated by ","type":"text"},{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","type":"reference","isActive":true},{"type":"text","text":" implementations."}],"url":"\/documentation\/vigramsdk\/bluetoothserviceerror","navigatorTitle":[{"kind":"identifier","text":"BluetoothServiceError"}]},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","type":"image","variants":[{"traits":["1x","light"],"url":"\/images\/logo.png"}]}}}