{"kind":"symbol","identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}],"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError"]]},"metadata":{"externalID":"s:9VigramSDK21BluetoothServiceErrorO12notConnectedyAC10Foundation4UUIDVcACmF","title":"BluetoothServiceError.notConnected(_:)","modules":[{"name":"VigramSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notConnected","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"text":")","kind":"text"}],"roleHeading":"Case","role":"symbol","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"notConnected"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier","text":"UUID"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothService":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","abstract":[{"text":"A BluetoothService is used to handle bluetooth connections.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"BluetoothService","kind":"identifier"}],"url":"\/documentation\/vigramsdk\/bluetoothservice","title":"BluetoothService","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BluetoothService","kind":"identifier"}]},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError":{"navigatorTitle":[{"kind":"identifier","text":"BluetoothServiceError"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError","abstract":[{"type":"text","text":"BluetoothServiceError lists different errors that can be propagated by "},{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothService","isActive":true,"type":"reference"},{"type":"text","text":" implementations."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BluetoothServiceError"}],"title":"BluetoothServiceError","type":"topic","url":"\/documentation\/vigramsdk\/bluetoothserviceerror"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/BluetoothServiceError/notConnected(_:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/BluetoothServiceError\/notConnected(_:)","abstract":[{"type":"text","text":"Connecting to a device failed unexplicably."}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"notConnected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UUID","preciseIdentifier":"s:10Foundation4UUIDV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"BluetoothServiceError.notConnected(_:)","url":"\/documentation\/vigramsdk\/bluetoothserviceerror\/notconnected(_:)"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"identifier":"logo.png","type":"icon"}],"title":"VigramSDK","url":"\/documentation\/vigramsdk","kind":"symbol","type":"topic","abstract":[],"role":"collection"},"logo.png":{"alt":"Vigram logo.","identifier":"logo.png","variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}],"type":"image"}}}