{"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/failure(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Authentication is failure - Other error received from server"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"VigramSDK"}],"externalID":"s:9VigramSDK19AuthenticationErrorO7failureyACSScACmF","title":"AuthenticationError.failure(_:)","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"failure","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failure(_:)":{"kind":"symbol","title":"AuthenticationError.failure(_:)","abstract":[{"text":"Authentication is failure - Other error received from server","type":"text"}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failure(_:)","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/failure(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failure","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"logo.png":{"variants":[{"url":"\/images\/logo.png","traits":["1x","light"]}],"type":"image","alt":"Vigram logo.","identifier":"logo.png"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationError","kind":"identifier"}],"type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror","abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"navigatorTitle":[{"text":"AuthenticationError","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","role":"symbol","title":"AuthenticationError"},"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"role":"collection","url":"\/documentation\/vigramsdk","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","images":[{"type":"icon","identifier":"logo.png"}],"type":"topic","title":"VigramSDK"}}}