{"variants":[{"paths":["\/documentation\/vigramsdk\/authenticationerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-6oo8g","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-7qgyt","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failureReason","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/helpAnchor","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/recoverySuggestion"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"VigramSDK"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError"]]},"references":{"doc://com.vigram.VigramSDK/documentation/VigramSDK":{"role":"collection","title":"VigramSDK","abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/helpAnchor":{"role":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/helpAnchor","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/helpanchor"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/failureReason":{"role":"symbol","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/failureReason","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/failurereason"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/recoverysuggestion"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/errorDescription-6oo8g":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-6oo8g","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/errordescription-6oo8g"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"AuthenticationError contains custom failure events when connecting to Authentication process."}],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/vigramsdk\/authenticationerror"},"doc://com.vigram.VigramSDK/documentation/VigramSDK/AuthenticationError/errorDescription-7qgyt":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.vigram.VigramSDK\/documentation\/VigramSDK\/AuthenticationError\/errorDescription-7qgyt","kind":"symbol","type":"topic","url":"\/documentation\/vigramsdk\/authenticationerror\/errordescription-7qgyt"}}}